### ISSUE TITLE
Add `undefined` check

### ISSUE THREAD

**Issue by michael-ciniawsky** [michael-ciniawsky/postcss-load-config#154]
### `Details`

Check for`undefined` in the plugin loader ([postcss-load-plugins #67](https://github.com/michael-ciniawsky/postcss-load-plugins/issues/67))

```diff
- if (options === null || Object.keys(options).length === 0)
+ if (options === null || options === undefined || Object.keys(options).length === 0)
```

Its being tested only if the options `{Object}` is `null`, if the `{Object}` is not `null` it tries to
look at the keys of the `{Object}`, but I believe that its being forgotten the case when the options `{Object}` is `undefined`

### `Error (Logs|Stacks)`

**postcss.config.js**
```js
module.exports = ({ file, options, env }) => {
    return {
        parser: file.extname === '.sss' ? 'sugarss' : false,
        plugins: {
            'postcss-import': { root: file.dirname },
            'postcss-cssnext': options.cssnext ? options.cssnext : false, // <=
            'autoprefixer': env == 'production' ? options.autoprefixer : false,
            'cssnano': env === 'production' ? options.cssnano : false
        }
    }
}
```

<details>

```
Module build failed: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at load (/home/matheus/Repositorios/fidelidade-online/node_modules/postcss-load-plugins/lib/plugins.js:42:38)
    at /home/matheus/Repositorios/fidelidade-online/node_modules/postcss-load-plugins/lib/plugins.js:66:18
    at Array.forEach (<anonymous>)
    at plugins (/home/matheus/Repositorios/fidelidade-online/node_modules/postcss-load-plugins/lib/plugins.js:65:8)
    at /home/matheus/Repositorios/fidelidade-online/node_modules/postcss-load-config/index.js:64:18
    at <anonymous>
```

</details>

### `Reproduction (Code)`

- Not needed

### `Environment`

- Not needed

**Comment by arthurbuhl** [comment]
I think maybe we can just do:

```diff
- if (options === null || options === undefined || Object.keys(options).length === 0)
+ if (!options || Object.keys(options).length === 0)
```

**Comment by michael-ciniawsky** [comment]
Would love to but `!options` coerces `null`, `false`, `undefined` to `false`, while `options === false ` means don't load this plugin  in `postcss-load-config` e.g

**postcssrc.js**
```js
module.exports = ({ options, env }) => {
  plugins: {
     'postcss-plugin': options.plugin  // Check or 'undefined', but load the plugin with defaults (the current bug)
     'cssnano': env === 'production' ? null : false // if env === 'development' don't load the plugin
  }
}
```

**Comment by arthurbuhl** [comment]
Ok, that make sense then.
