### ISSUE TITLE
Can't reexport shared configuration

### ISSUE THREAD

**Issue by hoschi** [michael-ciniawsky/postcss-load-config#73]
## Problem

I want to share my postcss config across packages, so I created one package which just holds the config:
my-postcss-config-pkg/index.js
```js
var prefixer = require('autoprefixer')({
  browsers: ['Explorer >= 11'],
})

module.exports = {
  plugins: [
    prefixer
  ],
};
```

In my app package I want to use it, so I created a postcss config there which just reexports the shared config:
app-pkg/postcss.config.js
```js
module.exports = require('my-postcss-config-pkg');
```
but this actually doesn't prefix anything. I also tested it with wrapping autoprefixer with a log statement and it does indeed only get called for one file which contains nothing to prefix anyway.

I found out that I need to use `Object.assign`:
```js
const config = require('my-postcss-config-pkg');
module.exports = Object.assign({}, config);
```
which makes totally no sense to me. Is this a bug?

## Environment

Please provide information about your environment.

| OS              | Node      | npm       | PostCSS   |
|:---------------:|:---------:|:---------:|:---------:|
| arch | 6.3.1 | 3.10.3 | postcss-loader 1.3.3 |

**Comment by michael-ciniawsky** [comment]
@hoschi Does the `require()` get resolved (Module Resolution)? Can you also post your `webpack.config.js` and where in your file tree you currently placed `postcss.config.js`? There is also `{Object}` notation for configs

**postcss.config.js**
```js
const options = {
   autoprefixer: { browsers: ['Explorer >= 11'] }
}

module.exports = (ctx) => ({
   plugins: {
      "autoprefixer": options.autoprefixer
   }
})
```
where `postcss-load-config` loads the plugin(s), but tbh I have no idea if that works 😛 

Could you also please use a CSS File where there would be definitely something to prefix or use another plugin ?

A small test repo with your current setup  for reproduction would be appreciated 🙃 

This definitely needs to be supported by `postcss-load-config` and was intended to, but after the config file worked I got bit lazy 🤣 💯

**Comment by hoschi** [comment]
> Does the require() get resolved (Module Resolution)?

yep, I tried REPL and it looks good

> Can you also post your webpack.config.js

See [1]

> where in your file tree you currently place postcss.config.js?

app-pkg/postcss.config.js means `app-pkg` is the root folder of this NPM module

> where postcss-load-config loads the plugin(s)

I had a lot of problems with other package which resolve stuff, so I try to use normal require as most as possible

> Could you also please use a CSS File where there would be definitely something to prefix or use another plugin ?

I think you mean this sentence from me:
I also tested it with wrapping autoprefixer with a log statement and it does indeed only get called for one file which contains nothing to prefix anyway.

I have a bunch of SCSS files which some should be prefixed and some not. Using
```js
module.exports = require('my-postcss-config-pkg');
```
then autoprefixer gets only called for one file (of say one hundred). This file doesn't contain anything to prefix, which is just a sidenote. But it should be called for each file, not only one. Using
```js
const config = require('my-postcss-config-pkg');
module.exports = Object.assign({}, config);
```
calls autoprefixer for each file. If there is something to prefix or not is moot, so this is the expected behavior.

> A small test repo with your current setup for reproduction would be appreciated

Do you have a starting repo with webpack and postcss already installed? I don't know how to start this.

[1]
```
'use strict';

// node core modules

// 3rd party modules
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CustomizationResolverPlugin = require('customization-resolver-webpack-plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

// internal modules
const { DEVELOPMENT, PRODUCTION, FRONTEND_MODULE_NAME } = require('../constants');
const { makeBabelOptions, makeBabelInclude, makeBabelExclude } = require('./babel-config-utils');
const { stringToRegex } = require('../util');

const globalStylesRegex = /styles-global\/.*\.scss$/;

const entryHmr = [
  'webpack-hot-middleware/client',
  'react-hot-loader/patch',
];

const pluginsDev = [
  new webpack.DefinePlugin({
    'process.env': {
      NODE_ENV: JSON.stringify(DEVELOPMENT),
    },
    __BASENAME__: JSON.stringify(process.env.BASENAME || ''),
  }),
  new webpack.HotModuleReplacementPlugin(),
  new webpack.NoEmitOnErrorsPlugin(),
];

const pluginsProd = [
  // move common dependencies into entry chunk, when it reduces the feature chunk by more than 50%
  new webpack.optimize.AggressiveMergingPlugin(),
  // extract CSS into own file to load it in parrallel with JS.
  // Also prevents FOUC, which should only happen with SSR.
  // https://webpack.js.org/guides/code-splitting/#css-splitting
  new ExtractTextPlugin({
    filename: 'app.css',
    // extract CSS of main module into CSS file, other chunk embedd their CSS in JS files
    allChunks: false,
    // we use CSS Modules so we can ignore this
    ignoreOrder: true,
  }),
  // set production as current environment, needed by webpack itself to activate some optimizations
  new webpack.DefinePlugin({
    'process.env': {
      NODE_ENV: JSON.stringify(PRODUCTION),
    },
    __BASENAME__: JSON.stringify(process.env.BASENAME || ''),
  }),
  // needs to be there till webpack 3:
  // * https://webpack.js.org/guides/migrating/#uglifyjsplugin-minimize-loaders
  // * https://webpack.js.org/plugins/loader-options-plugin/
  new webpack.LoaderOptionsPlugin({
    // put loaders into minimze mode
    minimize: true,
    // remove debug stuff
    debug: false,
  }),
  // minification
  new UglifyJsPlugin(),
];

const sassLoader = {
  loader: 'sass-loader',
  options: {
    sourceMap: true,
    sourceMapContents: true,
  },
};

const rulesDev = [{
  test: /\.css$/,
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      options: {
        modules: true,
        sourceMap: true,
        importLoaders: 1,
        localIdentName: '[name]__[local]__[hash:base64:5]',
      },
    },
    'postcss-loader',
  ],
}, {
  test: /\.scss$/,
  exclude: globalStylesRegex,
  use: [
    'style-loader?sourceMap',
    {
      loader: 'css-loader',
      options: {
        modules: true,
        sourceMap: true,
        importLoaders: 2,
        localIdentName: '[name]__[local]__[hash:base64:5]',
      },
    },
    'postcss-loader?sourceMap',
    sassLoader,
  ],
}, {
  test: globalStylesRegex,
  use: [
    'style-loader?sourceMap',
    'css-loader?sourceMap',
    'postcss-loader?sourceMap',
    sassLoader,
  ],
}];

const rulesProd = [{
  test: /\.css$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]__[hash:base64:5]',
      'postcss-loader',
    ],
  }),
}, {
  test: /\.scss$/,
  exclude: globalStylesRegex,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      'css-loader?modules&importLoaders=2&localIdentName=[name]__[local]__[hash:base64:5]',
      'postcss-loader',
      'sass-loader',
    ],
  }),
}, {
  test: globalStylesRegex,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      'css-loader',
      'postcss-loader',
      'sass-loader',
    ],
  }),
}];

function getLoaderQueryName(isDevelopment) {
  if (isDevelopment) {
    return '[path][name].[ext]?[hash]';
  }
  return '[hash].[ext]';
}

module.exports = function makeConfig(options) {
  const {
    isDevelopment,
    paths: {
      buildDir,
      customizationDir,
      customizationNodeModulesDir,
      file_frontendEntry,
      file_indexHtml,
      nodeModulesDir,
      srcDir,
    },
  } = options;

  const config = {
    entry: [
      // make babel-polyfill available for client code needed by
      // - runtime performance plugin transform-react-inline-elements
      // - redux-saga, because of the generators
      'babel-polyfill',
      // normal app entry point
      file_frontendEntry, // eslint-disable-line camelcase
    ],
    target: 'web',
    cache: isDevelopment,
    output: {
      path: buildDir,
      publicPath: '/',
    },
    module: {
      rules: [{
        test: /\.js?$/,
        include: makeBabelInclude(options.paths),
        exclude: makeBabelExclude(options.paths),
        use: {
          loader: 'babel-loader',
          options: makeBabelOptions(options),
        },
      }, {
        test: /\.txt$/,
        loader: 'raw-loader',
      }, {
        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2)$/,
        use: {
          loader: 'url-loader',
          options: {
            name: getLoaderQueryName(isDevelopment),
            limit: 10000,
          },
        },
      }, {
        test: /\.(eot|ttf|wav|mp3)$/,
        use: {
          loader: 'file-loader',
          options: {
            name: getLoaderQueryName(isDevelopment),
          },
        },
      },
      ],
    },
    // NOTE:
    // - commons plugin is only needed when you have multiple entry points, which not using all of your main entry point.
    plugins: [
      // inject generated file names into HTML
      new HtmlWebpackPlugin({
        template: file_indexHtml,
        hash: false,
        // favicon: set favicon here,
        filename: 'index.html',
        inject: 'body',
        minify: {
          collapseWhitespace: false,
        },
      }),
    ],
    stats: {
      // Nice colored output
      colors: true,
    },
    // make absolute import statements possible, also for local modules
    resolve: {
      // json added because some NPM module try to load json files via "require('./package')" instead of "require('./package.json')"
      extensions: ['.js', '.json'],
      modules: [
        customizationDir,
        srcDir,
        nodeModulesDir,
        customizationNodeModulesDir,
      ],
      plugins: [
        new CustomizationResolverPlugin({
          customizationDir,
          sourceDir: srcDir,
          isCompleteFileName: /\.scss$/,
          // exclude node_modules but not frontend if it lies under this path
          excludePath: stringToRegex(`node_modules(?!/${FRONTEND_MODULE_NAME})`),
          excludeRequest: stringToRegex(`node_modules(?!/${FRONTEND_MODULE_NAME})`),
        }),
      ],
    },
  };

  if (isDevelopment) {
    // add entries for HMR, ORDER MATTERS
    config.entry = [].concat(entryHmr).concat(config.entry);

    config.plugins = pluginsDev.concat(config.plugins);
    config.module.rules = rulesDev.concat(config.module.rules);

    // no hashing for file names
    config.output.filename = '[name].js';
    // now, take your poison ......
    // enable source maps for chrome devtools, see
    // * https://github.com/webpack/webpack/issues/3165
    // * https://github.com/webpack/webpack/issues/2145
    // config.devtool = 'inline-source-map';
    // use 'eval' because of stacktraces in rebox only supported by this devtool, breaks HMR in most cases
    config.devtool = 'eval';
  } else {
    config.plugins = pluginsProd.concat(config.plugins);
    config.module.rules = rulesProd.concat(config.module.rules);
    config.output.filename = '[name].[chunkhash].js';
  }

  return config;
};
```

**Comment by michael-ciniawsky** [comment]
uhhh...😩 😛 This config is way to complex...I have a test enviroment for webpack yep 👍 

1. Is your package on npm? (Link, Name)
2. Please narrow it down to just the CSS specific part (no "development/production", no plugins, ...), to make sure it's not related to your webpack setup :D
3. See below 😛 

### Package 

**package/package.json**
```json
{
   "name": "myPackage",
   "version": "1.0.0",
   "main": "index.js"
   "dependencies": {
       "postcss-plugin": "^1.0.0"
    }
}
```
package/index.js
```js
module.exports = (ctx) => ({
   plugins: [
     require('postcss-plugin')(ctx.options.plugin)
   ]
})
```

### Project

**project/postcss.config.js**
```js
module.exports = (ctx) => require('myPackage')(ctx) 
```

**project/webpack.config.js**
```js
{
   test: /\.css$/
   use: [ 'style-loader', { loader: 'css-loader, options: { importLoaders: 1 } }, 'postcss-loader' ]
}
```

**Comment by hoschi** [comment]
ok here you go:
```sh
git clone git@github.com:hoschi/postcss-load-config-issue-73-config.git config
git clone https://github.com/hoschi/postcss-load-config-issue-73-project project
cd project
npm install
npm install ../config
webpack
```

Gives me:
```sh
project > webpack
Hash: 0f7ed3ed8d2c7f7a0141
Version: webpack 2.3.1
Time: 405ms
    Asset     Size  Chunks             Chunk Names
bundle.js  15.9 kB       0  [emitted]  main
   [0] ./app/styles.css 1.05 kB {0} [built]
   [1] ./app/index.js 282 bytes {0} [built]
   [2] ./~/css-loader?{"importLoaders":1}!./~/postcss-loader!./app/styles.css 299 bytes {0} [built] [failed] [1 error]
   [3] ./~/style-loader/addStyles.js 8.51 kB {0} [built]
   [4] ./~/style-loader/fixUrls.js 3.01 kB {0} [built]

ERROR in ./~/css-loader?{"importLoaders":1}!./~/postcss-loader!./app/styles.css
Module build failed: TypeError: require(...) is not a function
    at module.exports (/home/hoschi/repos/postcss-load-config-issue-73/project/postcss.config.js:1:122)
    at /home/hoschi/repos/postcss-load-config-issue-73/project/node_modules/postcss-load-config/index.js:58:50
 @ ./app/styles.css 4:14-125
 @ ./app/index.js
```
Which I don't know why, have you an idea @michael-ciniawsky  ?

**Comment by michael-ciniawsky** [comment]
@hoschi [#1](https://github.com/hoschi/postcss-load-config-issue-73-config/issues/1)

**Comment by hoschi** [comment]
I changed the example repos to look like my setup from initial post and it works as expected in this minimal case:
```sh
project > webpack && cat dist/bundle.js  | grep block
Hash: c791c27d939007ea3ec1
Version: webpack 2.3.1
Time: 539ms
    Asset     Size  Chunks             Chunk Names
bundle.js  73.6 kB       0  [emitted]  main
   [0] ./app/styles.css 1.05 kB {0} [built]
   [1] ./app/index.js 282 bytes {0} [built]
   [2] ./~/base64-js/index.js 3.48 kB {0} [built]
   [3] ./~/buffer/index.js 48.6 kB {0} [built]
   [4] ./~/css-loader?{"importLoaders":1}!./~/postcss-loader!./app/styles.css 313 bytes {0} [built]
   [5] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
   [6] ./~/ieee754/index.js 2.05 kB {0} [built]
   [7] ./~/isarray/index.js 132 bytes {0} [built]
   [8] ./~/style-loader/addStyles.js 8.51 kB {0} [built]
   [9] ./~/style-loader/fixUrls.js 3.01 kB {0} [built]
  [10] (webpack)/buildin/global.js 509 bytes {0} [built]
exports.push([module.i, ".foo {\n\tdisplay: block;\n\t-webkit-user-select: none;\n\t   -moz-user-select: none;\n\t    -ms-user-select: none;\n\t        user-select: none;\n}\n", ""]);
```

**Comment by michael-ciniawsky** [comment]
@hoschi If you have time and interest also try with `{Object}` Notation 😛 , I will do later when I have time 😄. Exporting an `{Object}`should also work but the the signature changes an you lose `ctx`

**package/index.js**
```
modules.exports = {
   plugins: [
      ...plugins
   ]
}
```

**project/postcss.config.js**
```js
module.exports = require('package')
```

Can this be closed ? 🙃

**Comment by hoschi** [comment]
the output from my last comment is already with object notation ;)
We can close this as it seems to be a problem of some combination in my setup. If I have more information on this I post it here.

**Comment by hoschi** [comment]
Thanks for your help <3

**Comment by michael-ciniawsky** [comment]
> We can close this as it seems to be a problem of some combination in my setup. If I have more information on this I post it here

@hoschi 👍 Any regression or idea to improve the UX highly welcome, post it here or feel free to simply open a new issue 😛
